from django.urls import path

from . import views


app_name = "reports"

urlpatterns = [
    path("", views.index, name="index"),
    path("customers/", views.report_group, {"group_key": "customers"}, name="customer_reports"),
    path("suppliers/", views.report_group, {"group_key": "suppliers"}, name="supplier_reports"),
    path("sales/", views.report_group, {"group_key": "sales"}, name="sales_reports"),
    path("purchases/", views.report_group, {"group_key": "purchases"}, name="purchase_reports"),
    path("items/", views.report_group, {"group_key": "items"}, name="item_reports"),
    path("items/sales/", views.generic_report, {"report_key": "item_sales"}, name="item_sales"),
    path("items/purchases/", views.generic_report, {"report_key": "item_purchases"}, name="item_purchases"),
    path("items/profit/", views.generic_report, {"report_key": "item_profit"}, name="item_profit"),
    path("items/history/", views.generic_report, {"report_key": "item_history"}, name="item_history"),
    path("items/services-sales/", views.generic_report, {"report_key": "service_sales"}, name="service_sales"),
    path("services/", views.report_group, {"group_key": "services"}, name="service_reports"),
    path("accounting/", views.report_group, {"group_key": "accounting"}, name="accounting_reports"),
    path("tax/", views.report_group, {"group_key": "tax"}, name="tax_reports"),
    path("tax/summary/", views.generic_report, {"report_key": "tax_summary"}, name="tax_summary_root"),
    path("inventory/", views.report_group, {"group_key": "inventory"}, name="inventory_reports"),
    path("inventory/stock-balance/", views.generic_report, {"report_key": "inventory_stock_balance"}, name="inventory_stock_balance"),
    path("inventory/item-ledger/", views.generic_report, {"report_key": "inventory_item_ledger"}, name="inventory_item_ledger"),
    path("inventory/stock-in/", views.generic_report, {"report_key": "inventory_stock_in"}, name="inventory_stock_in"),
    path("inventory/stock-out/", views.generic_report, {"report_key": "inventory_stock_out"}, name="inventory_stock_out"),
    path("inventory/low-stock/", views.generic_report, {"report_key": "inventory_low_stock"}, name="inventory_low_stock"),
    path("inventory/valuation/", views.generic_report, {"report_key": "inventory_valuation"}, name="inventory_valuation"),
    path("customers/ledger/", views.generic_report, {"report_key": "customer_ledger"}, name="customer_ledger"),
    path("customers/outstanding/", views.generic_report, {"report_key": "customer_outstanding"}, name="customer_outstanding"),
    path("customers/aging/", views.generic_report, {"report_key": "customer_aging"}, name="customer_aging"),
    path("customers/statement/", views.generic_report, {"report_key": "customer_statement"}, name="customer_statement"),
    path("customers/sales/", views.generic_report, {"report_key": "customer_sales"}, name="customer_sales"),
    path("customers/receipts/", views.generic_report, {"report_key": "customer_receipts"}, name="customer_receipts"),
    path("suppliers/ledger/", views.generic_report, {"report_key": "supplier_ledger"}, name="supplier_ledger"),
    path("suppliers/payable/", views.generic_report, {"report_key": "supplier_payable"}, name="supplier_payable"),
    path("suppliers/aging/", views.generic_report, {"report_key": "supplier_aging"}, name="supplier_aging"),
    path("suppliers/statement/", views.generic_report, {"report_key": "supplier_statement"}, name="supplier_statement"),
    path("suppliers/purchases/", views.generic_report, {"report_key": "supplier_purchases"}, name="supplier_purchases"),
    path("suppliers/payments/", views.generic_report, {"report_key": "supplier_payments_summary"}, name="supplier_payments_summary"),
    path("sales/quotations/", views.generic_report, {"report_key": "sales_quotations"}, name="sales_quotations"),
    path("sales/confirmations/", views.generic_report, {"report_key": "sales_confirmations"}, name="sales_confirmations"),
    path("sales/delivery-challans/", views.generic_report, {"report_key": "sales_challans"}, name="sales_challans"),
    path("sales/invoices/", views.generic_report, {"report_key": "sales_invoices"}, name="sales_invoices"),
    path("sales/returns/", views.generic_report, {"report_key": "sales_returns"}, name="sales_returns"),
    path("sales/receipts/", views.generic_report, {"report_key": "receipts"}, name="receipts"),
    path("sales/tax/", views.generic_report, {"report_key": "sales_tax"}, name="sales_tax"),
    path("purchases/purchases/", views.generic_report, {"report_key": "purchase_report"}, name="purchase_report"),
    path("purchases/returns/", views.generic_report, {"report_key": "purchase_returns"}, name="purchase_returns"),
    path("purchases/payments/", views.generic_report, {"report_key": "supplier_payments"}, name="supplier_payments"),
    path("purchases/tax/", views.generic_report, {"report_key": "purchase_tax"}, name="purchase_tax"),
    path("purchases/profit-by-invoice/", views.generic_report, {"report_key": "profit_by_invoice"}, name="profit_by_invoice"),
    path("purchases/profit-by-confirmation/", views.generic_report, {"report_key": "profit_by_confirmation"}, name="profit_by_confirmation"),
    path("services/contracts/", views.generic_report, {"report_key": "service_contracts"}, name="service_contracts"),
    path("services/expiring/", views.generic_report, {"report_key": "service_expiring"}, name="service_expiring"),
    path("services/billing-due/", views.generic_report, {"report_key": "service_billing_due"}, name="service_billing_due"),
    path("services/invoice-history/", views.generic_report, {"report_key": "service_invoice_history"}, name="service_invoice_history"),
    path("accounting/cash-book/", views.generic_report, {"report_key": "cash_book"}, name="cash_book"),
    path("accounting/bank-book/", views.generic_report, {"report_key": "bank_book"}, name="bank_book"),
    path("accounting/general-ledger/", views.generic_report, {"report_key": "general_ledger"}, name="general_ledger"),
    path("accounting/trial-balance/", views.generic_report, {"report_key": "trial_balance"}, name="trial_balance"),
    path("accounting/profit-loss/", views.generic_report, {"report_key": "profit_loss"}, name="profit_loss"),
    path("accounting/balance-sheet/", views.generic_report, {"report_key": "balance_sheet"}, name="balance_sheet"),
    path("accounting/journals/", views.generic_report, {"report_key": "journal_report"}, name="journal_report"),
    path("accounting/expenses/", views.generic_report, {"report_key": "expense_report"}, name="expense_report"),
    path("accounting/income/", views.generic_report, {"report_key": "income_report"}, name="income_report"),
    path("accounting/tax-summary/", views.generic_report, {"report_key": "tax_summary"}, name="tax_summary"),
    path("accounting/account-ledger/", views.generic_report, {"report_key": "account_ledger"}, name="account_ledger"),
    path("system/", views.report_group, {"group_key": "system"}, name="system_reports"),
    path("system/activity/", views.generic_report, {"report_key": "system_activity"}, name="system_activity"),
    path("system/login-logout/", views.generic_report, {"report_key": "system_login_logout"}, name="system_login_logout"),
    path("system/prints/", views.generic_report, {"report_key": "system_prints"}, name="system_prints"),
    path("system/exports/", views.generic_report, {"report_key": "system_exports"}, name="system_exports"),
    path("system/backup-restore/", views.generic_report, {"report_key": "system_backup_restore"}, name="system_backup_restore"),
    path("system/validation-failures/", views.generic_report, {"report_key": "system_validation_failures"}, name="system_validation_failures"),
]
