from django.urls import path

from . import views


app_name = "sales"

urlpatterns = [
    path("", views.index, name="index"),
    path("quotations/", views.quotations_list, name="quotations"),
    path("quotations/new/", views.quotation_form, name="quotation_new"),
    path("quotations/<int:quotation_id>/", views.quotation_detail, name="quotation_detail"),
    path("quotations/<int:quotation_id>/edit/", views.quotation_form, name="quotation_edit"),
    path("quotations/<int:quotation_id>/duplicate/", views.duplicate_quotation, name="quotation_duplicate"),
    path("quotations/<int:quotation_id>/add-as-customer/", views.add_as_customer, name="quotation_add_as_customer"),
    path("quotations/<int:quotation_id>/cancel/", views.cancel_quotation, name="quotation_cancel"),
    path("quotations/<int:quotation_id>/print/", views.print_quotation, name="quotation_print"),
    path("quotations/<int:quotation_id>/pdf/", views.pdf_quotation, name="quotation_pdf"),
    path("quotations/<int:quotation_id>/classic-print/", views.classic_print_quotation, name="quotation_classic_print"),
    path("quotations/<int:quotation_id>/classic-pdf/", views.classic_pdf_quotation, name="quotation_classic_pdf"),
    path("quotations/<int:quotation_id>/convert-to-confirmation/", views.convert_to_confirmation, name="quotation_convert"),
    path("confirmations/", views.confirmations_list, name="confirmations"),
    path("confirmations/new/", views.confirmation_form, name="confirmation_new"),
    path("confirmations/from-quotation/<int:quotation_id>/", views.confirmation_form, name="confirmation_from_quotation"),
    path("confirmations/<int:confirmation_id>/", views.confirmation_detail, name="confirmation_detail"),
    path("confirmations/<int:confirmation_id>/edit/", views.confirmation_form, name="confirmation_edit"),
    path("confirmations/<int:confirmation_id>/cancel/", views.cancel_confirmation, name="confirmation_cancel"),
    path("confirmations/<int:confirmation_id>/print/", views.print_confirmation, name="confirmation_print"),
    path("delivery-challans/", views.delivery_challans_list, name="delivery_challans"),
    path("delivery-challans/new/", views.delivery_challan_form, name="delivery_challan_new"),
    path("delivery-challans/from-confirmation/<int:confirmation_id>/", views.delivery_challan_form, name="delivery_challan_from_confirmation"),
    path("delivery-challans/from-quotation/<int:quotation_id>/", views.delivery_challan_form, name="delivery_challan_from_quotation"),
    path("delivery-challans/<int:challan_id>/", views.delivery_challan_detail, name="delivery_challan_detail"),
    path("delivery-challans/<int:challan_id>/edit/", views.delivery_challan_form, name="delivery_challan_edit"),
    path("delivery-challans/<int:challan_id>/cancel/", views.cancel_delivery_challan, name="delivery_challan_cancel"),
    path("delivery-challans/<int:challan_id>/print/", views.print_delivery_challan, name="delivery_challan_print"),
    path("delivery-challans/<int:challan_id>/upload-signed-copy/", views.upload_signed_challan, name="delivery_challan_upload_signed"),
    path("invoices/", views.invoices_list, name="invoices"),
    path("invoices/new/", views.invoice_form, name="invoice_new"),
    path("invoices/from-dc/<int:dc_id>/", views.invoice_form, name="invoice_from_dc"),
    path("invoices/from-confirmation/<int:confirmation_id>/", views.invoice_form, name="invoice_from_confirmation"),
    path("invoices/from-quotation/<int:quotation_id>/", views.invoice_form, name="invoice_from_quotation"),
    path("invoices/<int:invoice_id>/", views.invoice_detail, name="invoice_detail"),
    path("invoices/<int:invoice_id>/edit/", views.invoice_form, name="invoice_edit"),
    path("invoices/<int:invoice_id>/cancel/", views.cancel_invoice, name="invoice_cancel"),
    path("invoices/<int:invoice_id>/print/", views.print_invoice, name="invoice_print"),
    path("invoices/<int:invoice_id>/digital-print/", views.digital_print_invoice, name="invoice_digital_print"),
    path("invoices/<int:invoice_id>/classic-print/", views.classic_print_invoice, name="invoice_classic_print"),
    path("invoices/<int:invoice_id>/classic-pdf/", views.classic_pdf_invoice, name="invoice_classic_pdf"),
    path("receipts/", views.receipts_list, name="receipts"),
    path("receipts/new/", views.receipt_form, name="receipt_new"),
    path("receipts/from-invoice/<int:invoice_id>/", views.receipt_form, name="receipt_from_invoice"),
    path("receipts/<int:receipt_id>/", views.receipt_detail, name="receipt_detail"),
    path("receipts/<int:receipt_id>/edit/", views.receipt_form, name="receipt_edit"),
    path("receipts/<int:receipt_id>/cancel/", views.cancel_receipt, name="receipt_cancel"),
    path("receipts/<int:receipt_id>/print/", views.print_receipt, name="receipt_print"),
    path("returns/", views.sales_returns_list, name="returns"),
    path("returns/new/", views.sales_return_form, name="return_new"),
    path("returns/from-invoice/<int:invoice_id>/", views.sales_return_form, name="return_from_invoice"),
    path("returns/invoice-items/<int:invoice_id>/", views.sales_return_invoice_items, name="return_invoice_items"),
    path("returns/<int:return_id>/", views.sales_return_detail, name="return_detail"),
    path("returns/<int:return_id>/edit/", views.sales_return_form, name="return_edit"),
    path("returns/<int:return_id>/cancel/", views.cancel_sales_return, name="return_cancel"),
    path("returns/<int:return_id>/print/", views.print_sales_return, name="return_print"),
]
